# 作業 : (Kaggle)鐵達尼生存預測
***
- 分數以網站評分結果為準, 請同學實際將提交檔(*.csv)上傳試試看  
https://www.kaggle.com/c/titanic/submit

# [作業目標]
- 試著模仿範例寫法, 在鐵達尼生存預測中, 觀察觀查混合泛化 (Blending) 的寫法與效果

# [作業重點]
- 觀察混合泛化的準確度 (In[14]), 是否比單一模型準確度為高 (In[11~13])  
- 除了我們的權重, 同學也可以試著自行調整權重 (注意:權重和=1), 看看有什麼影響
- Hint : 除了權重, 分類預測的調整, 還可以調整什麼地方?

In [4]:
# 做完特徵工程前的所有準備 (與前範例相同)
import pandas as pd
import numpy as np
import copy, time
import warnings
warnings.filterwarnings('ignore')
from IPython.display import display
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

data_path = '/Users/kuangtinghsiao/Documents/資料科學馬拉松/Part02-1/'
df_train = pd.read_csv(data_path + 'titanic_train.csv')
df_test = pd.read_csv(data_path + 'titanic_test.csv')

train_Y = df_train['Survived']
ids = df_test['PassengerId']
df_train = df_train.drop(['PassengerId', 'Survived'] , axis=1)
df_test = df_test.drop(['PassengerId'] , axis=1)
df = pd.concat([df_train,df_test])
df.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
# 檢查 DataFrame 空缺值的狀態
def na_check(df_data):
    data_na = (df_data.isnull().sum() / len(df_data)) * 100
    data_na = data_na.drop(data_na[data_na == 0].index).sort_values(ascending=False)
    missing_data = pd.DataFrame({'Missing Ratio' :data_na})
    display(missing_data.head(10))
na_check(df)

          Missing Ratio
Cabin         77.463713
Age           20.091673
Embarked       0.152788
Fare           0.076394

In [6]:
# 以下 In[3]~In[10] 只是鐵達尼預測中的一組特徵工程, 並以此組特徵工程跑參數, 若更換其他特徵工程, In[10]的參數需要重新跑
# Sex : 直接轉男 0 女 1
df["Sex"] = df["Sex"].map({"male": 0, "female":1})
# Fare : 用 log 去偏態, 0 則直接取 0
df["Fare"] = df["Fare"].map(lambda i: np.log(i) if i > 0 else 0)
# Age : 缺值用中位數補
df["Age"] = df["Age"].fillna(df['Age'].median())

In [7]:
# Title 的 特徵工程 : 將各種頭銜按照類型分類, 最後取 One Hot
df_title = [i.split(",")[1].split(".")[0].strip() for i in df["Name"]]
df["Title"] = pd.Series(df_title)
df["Title"] = df["Title"].replace(['Lady', 'the Countess','Countess','Capt', 'Col','Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')
df["Title"] = df["Title"].map({"Master":0, "Miss":1, "Ms" : 1 , "Mme":1, "Mlle":1, "Mrs":1, "Mr":2, "Rare":3})
df["Title"] = df["Title"].astype(int)
df = pd.get_dummies(df, columns = ["Title"])

In [12]:
# 新建:家庭大小 (Fsize)特徵, 並依照大小分別建獨立欄位
df["Fsize"] = df["SibSp"] + df["Parch"] + 1
df['Single'] = df['Fsize'].map(lambda s: 1 if s == 1 else 0)
df['SmallF'] = df['Fsize'].map(lambda s: 1 if  s == 2  else 0)
df['MedF'] = df['Fsize'].map(lambda s: 1 if 3 <= s <= 4 else 0)
df['LargeF'] = df['Fsize'].map(lambda s: 1 if s >= 5 else 0)

In [18]:
# Ticket : 如果不只是數字-取第一個空白之前的字串(去除'.'與'/'), 如果只是數字-設為'X', 最後再取 One Hot
Ticket = []
for i in list(df.Ticket):
    if not i.isdigit() :
        Ticket.append(i.replace(".","").replace("/","").strip().split(' ')[0])
    else:
        Ticket.append("X")        
df["Ticket"] = Ticket
df = pd.get_dummies(df, columns = ["Ticket"], prefix="T")

KeyError: 'Ticket'

In [19]:
# Cabib 依照第一碼分類, 再取 One Hot
df["Cabin"] = pd.Series([i[0] if not pd.isnull(i) else 'X' for i in df['Cabin'] ])
df = pd.get_dummies(df, columns = ["Cabin"], prefix="Cabin")

In [20]:
# Embarked, Pclass 取 One Hot
df = pd.get_dummies(df, columns = ["Embarked"], prefix="Em")
df["Pclass"] = df["Pclass"].astype("category")
df = pd.get_dummies(df, columns = ["Pclass"], prefix="Pc")

# 捨棄 Name 欄位
df.drop(labels = ["Name"], axis = 1, inplace = True)

In [21]:
# 確認缺值 與 目前的資料表內容
na_check(df)
df.head()

Empty DataFrame
Columns: [Missing Ratio]
Index: []

,Sex,Age,SibSp,Parch,Fare,Title_0,Title_1,Title_2,Title_3,Fsize,...,Cabin_F,Cabin_G,Cabin_T,Cabin_X,Em_C,Em_Q,Em_S,Pc_1,Pc_2,Pc_3
0,0,22.0,1,0,1.981001,0,0,1,0,2,...,0,0,0,1,0,0,1,0,0,1
1,1,38.0,1,0,4.266662,0,1,0,0,2,...,0,0,0,0,1,0,0,1,0,0
2,1,26.0,0,0,2.070022,0,1,0,0,1,...,0,0,0,1,0,0,1,0,0,1
3,1,35.0,1,0,3.972177,0,1,0,0,2,...,0,0,0,0,0,0,1,1,0,0
4,0,35.0,0,0,2.085672,0,0,1,0,1,...,0,0,0,1,0,0,1,0,0,1

In [22]:
# 將資料最大最小化
df = MinMaxScaler().fit_transform(df)

# 將前述轉換完畢資料 df , 重新切成 train_X, test_X
train_num = train_Y.shape[0]
train_X = df[:train_num]
test_X = df[train_num:]

# 使用三種模型 : 邏輯斯迴歸 / 梯度提升機 / 隨機森林, 參數使用 Random Search 尋找
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
lr = LogisticRegression(tol=0.001, penalty='l2', fit_intercept=True, C=1.0)
gdbt = GradientBoostingClassifier(tol=100, subsample=0.75, n_estimators=250, max_features=20,
                                  max_depth=6, learning_rate=0.03)
rf = RandomForestClassifier(n_estimators=100, min_samples_split=2, min_samples_leaf=1, 
                            max_features='sqrt', max_depth=6, bootstrap=True)

In [28]:
# 線性迴歸預測檔 (結果有部分隨機, 請以 Kaggle 計算的得分為準, 以下模型同理)
lr.fit(train_X, train_Y)
lr_pred = lr.predict_proba(test_X)[:,1]
sub = pd.DataFrame({'PassengerId': ids, 'Survived': lr_pred})
sub['Survived'] = sub['Survived'].map(lambda x:1 if x>0.5 else 0) 
sub.to_csv('titanic_lr.csv', index=False)

In [29]:
# 梯度提升機預測檔 
gdbt.fit(train_X, train_Y)
gdbt_pred = gdbt.predict_proba(test_X)[:,1]
sub = pd.DataFrame({'PassengerId': ids, 'Survived': gdbt_pred})
sub['Survived'] = sub['Survived'].map(lambda x:1 if x>0.5 else 0) 
sub.to_csv('titanic_gdbt.csv', index=False)

In [30]:
# 隨機森林預測檔
rf.fit(train_X, train_Y)
rf_pred = rf.predict_proba(test_X)[:,1]
sub = pd.DataFrame({'PassengerId': ids, 'Survived': rf_pred})
sub['Survived'] = sub['Survived'].map(lambda x:1 if x>0.5 else 0) 
sub.to_csv('titanic_rf.csv', index=False)

# 作業
* 雖然同樣是混合泛化，分類預測其實與回歸預測有相當多的差異性，
因為鐵達尼預測的結果是 '生存/死亡'，輸出不是 0 就是 1  
因此要用權重混合時，需要以以機率的形式混合，因此我們在作業前幾格當中，先幫各位同學把預測值寫成了機率的形式  
(請同學把下列程式完成，並將結果提交到 Kaggle 網站看看結果)

* 但是光是這樣，分類問題的混合泛化就能比單模預測還要好嗎?  
已經快要期中考了，這裡請同學挑戰看看，還有沒有什麼方法可以改進混合泛化的結果?

In [33]:
# 混合泛化預測檔 
"""
Your Code Here
"""
blending_pred = lr_pred*0.3  + gdbt_pred*0.3 + rf_pred*0.3

sub = pd.DataFrame({'PassengerId': ids, 'Survived': blending_pred})
sub['Survived'] =  sub['Survived'].map(lambda x:0 if x<0.5 else 0)
sub.to_csv('titanic_blending.csv', index=False)

In [32]:
blending_pred

array([0.0808687 , 0.3751562 , 0.39018213, 0.41152241, 0.19240519,
       0.07874513, 0.40970888, 0.66772458, 0.68925519, 0.28726429,
       0.26600266, 0.53602051, 0.48474387, 0.07378046, 0.76091209,
       0.80179194, 0.57662328, 0.16575975, 0.46849856, 0.48363069,
       0.14934113, 0.23723398, 0.80302094, 0.32369962, 0.69278918,
       0.19674916, 0.56880746, 0.17701978, 0.59142515, 0.12936822,
       0.17301913, 0.67623498, 0.60565628, 0.12347821, 0.3156847 ,
       0.15672271, 0.19767106, 0.18797847, 0.2796317 , 0.46120741,
       0.31788299, 0.62465161, 0.06937739, 0.76322027, 0.78940941,
       0.1771811 , 0.17373625, 0.41888584, 0.49769734, 0.60778613,
       0.68193305, 0.1784378 , 0.83443635, 0.61049467, 0.27313723,
       0.11046466, 0.24134263, 0.08298649, 0.34193808, 0.79125387,
       0.06981944, 0.66847531, 0.09689548, 0.65187164, 0.14118167,
       0.75932398, 0.69585184, 0.1665152 , 0.67384582, 0.24871238,
       0.26938684, 0.26092683, 0.22240198, 0.18522999, 0.64140133,
       0.49277971, 0.0773321 , 0.36841863, 0.58797298, 0.63827277,
       0.18674176, 0.13645974, 0.51094926, 0.07032747, 0.51341559,
       0.3232795 , 0.36727396, 0.19429178, 0.66525285, 0.22659607,
       0.17104691, 0.08937378, 0.63953117, 0.0773321 , 0.29827259,
       0.10081432, 0.59692082, 0.48107179, 0.52595474, 0.06309315,
       0.81972657, 0.10121089, 0.19664294, 0.0980895 , 0.22871681,
       0.10950242, 0.41577587, 0.09835815, 0.0798063 , 0.46061539,
       0.174133  , 0.64428609, 0.46439342, 0.62900858, 0.79318516,
       0.10017713, 0.08671476, 0.36493721, 0.48904796, 0.77225007,
       0.35203062, 0.08298016, 0.59233247, 0.60564592, 0.19664294,
       0.64789247, 0.10056148, 0.40513316, 0.58623113, 0.0731229 ,
       0.08745008, 0.19628583, 0.14508203, 0.35242429, 0.0623274 ,
       0.08074822, 0.63620795, 0.19683493, 0.21123488, 0.09735061,
       0.10755676, 0.82253065, 0.45114203, 0.12943603, 0.27654111,
       0.0938565 , 0.2295299 , 0.27204431, 0.40890149, 0.2242999 ,
       0.69733549, 0.46618719, 0.04410772, 0.18915096, 0.04163406,
       0.05935718, 0.82814264, 0.22245388, 0.27654111, 0.61751755,
       0.26691572, 0.50620629, 0.33706336, 0.08137288, 0.54385732,
       0.6339864 , 0.74436686, 0.06132736, 0.57776674, 0.19154762,
       0.07531783, 0.62135149, 0.29332693, 0.10368113, 0.14008961,
       0.39501332, 0.76296237, 0.72204154, 0.38627227, 0.42415853,
       0.50768233, 0.22347046, 0.78421376, 0.58300102, 0.83008424,
       0.18102391, 0.66443492, 0.06628944, 0.05448067, 0.10625737,
       0.50525504, 0.18536488, 0.37832311, 0.56299782, 0.7483563 ,
       0.39978107, 0.44578939, 0.20478845, 0.45763886, 0.43797484,
       0.27018546, 0.18361308, 0.20012783, 0.36492708, 0.09791119,
       0.62991662, 0.19443377, 0.09933462, 0.81982165, 0.09928308,
       0.12523594, 0.27439817, 0.11059678, 0.25863512, 0.13088214,
       0.72039881, 0.65790874, 0.18180254, 0.86184825, 0.0773321 ,
       0.43855423, 0.07328053, 0.24227152, 0.11974175, 0.33425351,
       0.26135726, 0.08799844, 0.2828158 , 0.06542604, 0.46866315,
       0.66482494, 0.52500111, 0.06469473, 0.43433676, 0.20076272,
       0.31834192, 0.18914175, 0.53082885, 0.33271107, 0.50695956,
       0.7909586 , 0.77191346, 0.32797244, 0.07031926, 0.05709701,
       0.47407277, 0.79403778, 0.53405227, 0.60088393, 0.2867742 ,
       0.44695496, 0.28874219, 0.41196168, 0.07327368, 0.27890273,
       0.35195754, 0.41867891, 0.39404385, 0.74962548, 0.31099017,
       0.06327984, 0.50208261, 0.65459516, 0.46274251, 0.57854291,
       0.07032747, 0.10702425, 0.06631558, 0.48884808, 0.37716689,
       0.2690037 , 0.09835815, 0.83117321, 0.34165984, 0.47803354,
       0.82958502, 0.48303956, 0.09422081, 0.62581478, 0.32951831,
       0.18830576, 0.29140813, 0.2828158 , 0.25108646, 0.3912258 ,
       0.05339165, 0.0655556 , 0.2149818 , 0.10368113, 0.2265366 ,
       0.56827735, 0.47339989, 0.20868183, 0.6286053 , 0.07527743,
       0.07673717, 0.48987873, 0.57313012, 0.27282374, 0.4360888 ,
       0.280502  , 0.14749422, 0.05996063, 0.53920437, 0.2828158 ,
       0.7908022 , 0.62520459, 0.4536662 , 0.19729055, 0.55955508,
       0.37509053, 0.60531083, 0.31882257, 0.17674457, 0.41529852,
       0.68284328, 0.63087115, 0.15430578, 0.45816006, 0.72022168,
       0.0980895 , 0.12539335, 0.46904304, 0.63615703, 0.56479864,
       0.36183165, 0.3595373 , 0.77330178, 0.51061516, 0.60579852,
       0.78623073, 0.24682646, 0.127212  , 0.373772  , 0.32271267,
       0.18383431, 0.22558703, 0.45885448, 0.12440178, 0.11708918,
       0.67635809, 0.35184768, 0.03534028, 0.46008112, 0.06823507,
       0.64960653, 0.46904304, 0.48851993, 0.54002385, 0.45443342,
       0.44787295, 0.19019964, 0.10996798, 0.11643362, 0.30366512,
       0.14806692, 0.83176359, 0.32074251, 0.41888584, 0.52904059,
       0.02835179, 0.43694921, 0.7837867 , 0.11879085, 0.58236717,
       0.07173245, 0.57299263, 0.56208849, 0.82736402, 0.7308386 ,
       0.34689134, 0.63997734, 0.08821146, 0.10158065, 0.81295726,
       0.8380409 , 0.37521098, 0.1623833 , 0.14448664, 0.09314986,
       0.41888584, 0.44597942, 0.21524288, 0.52811277, 0.19320122,
       0.37229815, 0.4949716 , 0.37376468, 0.09555352, 0.08101954,
       0.37848177, 0.35376226, 0.10464436, 0.60112517, 0.1530518 ,
       0.47975096, 0.36830491, 0.59449209, 0.13958876, 0.32776699,
       0.56619723, 0.09000494, 0.8386427 , 0.20757497, 0.59793568,
       0.2833898 , 0.09127853, 0.73643817, 0.25158023, 0.67281472,
       0.2828158 , 0.58004933, 0.56620005, 0.06562176, 0.53406054,
       0.21965378, 0.2674847 , 0.49714485])